name: Send a Tweet
on: [push]
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: devigned/go-twitter-action@v1.0.2
        with:
          message: "NEW POST FROM GITHUB!"
          apiKey: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          apiKeySecret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          accessToken: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          accessTokenSecret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
